import sys
from dataclasses import dataclass
from pathlib import Path
from random import gauss, uniform, randint
from typing import List, Optional

import pygame

# This line tells python how to handle the relative imports
# when you run this file directly. Don't modify this line.
__package__ = "04-bouncing-bubbles." + Path(__file__).absolute().parent.name

# To import the modules in yourname/, you need to use relative imports,
# otherwise your project will not be compatible with the showcase.
from .utils import *

BACKGROUND = 0x0F1012
NB_BUBBLES = 30
CORRECTION_FACTOR = 10


class Bubble:
    MAX_VELOCITY = 7

    def __init__(self, r: float, xy: pygame.Vector2, color=None, parent: 'Bubble' = None):
        self.r = r
        self.xy = xy

        self.parent = parent
        if self.parent is not None:
            self.parent._add_child(self)
        self.depth = 0 if self.parent is None else self.parent.depth + 1

        # Set a random direction and a speed of around 3.
        self.v_xy = pygame.Vector2()
        self.v_xy.from_polar((gauss(3, 0.5), uniform(0, 360)))
        self.v_accum = pygame.Vector2(0, 0)

        # Pick a random color with high saturation and value.
        if color is None:
            self.color = pygame.Color(0)
            self.color.hsva = uniform(0, 360), 80, 80, 100
        else:
            self.color = color

        self.children = []

    def _add_child(self, bubble):
        self.children.append(bubble)

    @property
    def mass(self):
        return self.r ** 2

    def draw(self, screen: pygame.Surface, offs=pygame.Vector2(0, 0)):
        for c in self.children:
            c.draw(screen, offs=self.xy + offs)
        pygame.draw.circle(screen, self.color, self.xy + offs, self.r, width=1)

    def move_away_from_mouse(self, mouse_pos: pygame.Vector2):
        """Apply a force on the bubble to move away from the mouse."""
        bubble_to_mouse = mouse_pos - self.xy
        distance_to_mouse = bubble_to_mouse.length()
        if 0 < distance_to_mouse < 200:
            strength = chrange(distance_to_mouse, (0, 200), (1, 0), power=2)
            self.v_xy -= bubble_to_mouse.normalize() * strength

    def move(self):
        """Move the bubble according to its velocity."""
        # We first limit the velocity to not get bubbles that go faster than what we can enjoy.
        if self.v_xy.length() > self.MAX_VELOCITY:
            self.v_xy.scale_to_length(self.MAX_VELOCITY)

        self.xy += self.v_xy
        debug.vector(self.v_xy, self.v_xy, scale=10)

    def collide_borders(self):
        # The first challenge is to make the bubbles bounce against the border.
        # However that doesn't mean that a bubble must always be completely inside of the screen:
        # If for instance it spawned on the edge, we don't want it to teleport so that it fits the screen,
        # we want everything to be *smooooth*.
        #
        # To be sure it is smooth, a good rule is to never modify self.position directly,
        # but instead modify self.velocity when needed.
        #
        # The second golden principle is to be lazy and not do anything if the collision will
        # resolve itself naturally in a few frames, that is, if the bubble is already moving
        # away from the wall.

        if self.parent is None:
            # top-level bubble, bounce off screen borders
            if self.xy[0] - self.r < 0 and self.v_xy[0] < 0:
                self.v_xy[0] *= -1
            elif self.xy[0] + self.r >= SIZE[0] and self.v_xy[0] > 0:
                self.v_xy[0] *= -1

            if self.xy[1] - self.r < 0 and self.v_xy[1] < 0:
                self.v_xy[1] *= -1
            elif self.xy[1] + self.r >= SIZE[1] and self.v_xy[1] > 0:
                self.v_xy[1] *= -1
        else:
            pass  # TODO child-parent collisions

    def collide(self, other: "Bubble") -> Optional["Collision"]:
        """Get the collision data if there is a collision with the other Bubble"""
        if 0 < self.xy.distance_to(other.xy) < self.r + other.r:
            return Collision(first=self,
                             second=other,
                             center=(self.xy + other.xy) / 2,
                             normal=(self.xy - other.xy).rotate(90).normalize())
        else:
            return None


# The second challenge contains two parts.
# The first one is to generate a list of all the collisions
# between bubbles.
# The data for a collision is stored into the Collision class below,
# and is generated by the Bubble.collide method above.
# The second part is then to process those collision data, and resolve them.

@dataclass
class Collision:
    """
    The data of a collision consist of four attributes.

    [first] and [second] are the the two objects that collided.
    [center] is the collision point, that is, the point from which you
        would like to push both circles away from. It corresponds to the center
        of the overlapping area of the two moving circles, which is also the
        midpoint between the two centers.
    [normal] is the axis along which the two circles should bounce. That is,
        if two bubbles move horizontally they bounce against the vertical axis,
        so normal would be a vertical vector.
    """

    first: "Bubble"
    second: "Bubble"
    center: pygame.Vector2
    normal: pygame.Vector2

    def resolve(self):
        """Apply a force on both colliding object to help them move out of collision."""

        xy1 = self.first.xy
        xy2 = self.second.xy

        overlap = (self.first.r + self.second.r) - xy1.distance_to(xy2)

        pcnt_overlap_1 = min(1.0, overlap / self.first.r)
        correction1 = CORRECTION_FACTOR * pcnt_overlap_1 * (xy1 - xy2).normalize()
        self.first.v_xy += correction1

        pcnt_overlap_2 = min(1.0, overlap / self.second.r)
        correction2 = CORRECTION_FACTOR * pcnt_overlap_2 * (xy2 - xy1).normalize()
        self.second.v_xy += correction2

        # momentum = v1 * self.first.mass + v2 * self.second.mass
        # n = self.normal
        #
        # # only care if they're moving towards each other
        # if v1.dot(xy2 - xy1) > 0:
        #     v1_new = reflect(v1, n)
        #     self.first.v_accum += v1_new - v1
        # if v1.dot(xy1 - xy1) > 0:
        #     v2_new = reflect(v2, n)
        #     self.second.v_accum += v2_new - v2


def reflect(v1: pygame.Vector2, v2: pygame.Vector2):
        k = v1.dot(v2) / v2.dot(v2)
        return 2*k*v2 - v1


# The world is a list of bubbles.
class World(List[Bubble]):
    def __init__(self, nb):
        super().__init__(Bubble(50, pygame.Vector2(300, 200)) for _ in range(nb))

    def logic(self, mouse_position: pygame.Vector2):
        """Handles the collision and evolution of all the objects."""

        # Second part of the ambitious challenge is to make the algorithm that solves the collisions.
        # A part of it is already provided so that you can focus on the important part.

        # We start by moving the bubbles and do the collisions with the static objects, the walls.
        for bubble in self:
            bubble.move()
            bubble.collide_borders()
            bubble.move_away_from_mouse(mouse_position)

        # Then we check each pair of bubbles to collect all collisions.
        collisions = []
        for i, b1 in enumerate(self):
            for b2 in self[i + 1 :]:  # holy N^2 batman
                collision = b1.collide(b2)
                if collision:
                    collisions.append(collision)

        # And finally we resolve them all at once, so that it doesn't impact the detection of collision.
        for collision in collisions:
            collision.resolve()

    def draw(self, screen):
        for bubble in self:
            bubble.draw(screen)


def mainloop():
    pygame.init()

    world = World(NB_BUBBLES)

    mouse_position = pygame.Vector2()

    fps_counter = FpsCounter(60, Bubbles=world)
    while True:
        screen, events = yield
        for event in events:
            if event.type == pygame.QUIT:
                return
            elif event.type == pygame.MOUSEMOTION:
                mouse_position.xy = event.pos
            elif event.type == pygame.MOUSEBUTTONDOWN:
                world.append(Bubble(randint(10, 30), event.pos))
            debug.handle_event(event)
            fps_counter.handle_event(event)

        # Handle the collisions
        world.logic(mouse_position)
        fps_counter.logic()

        # Drawing the screen
        screen.fill(BACKGROUND)
        world.draw(screen)
        fps_counter.draw(screen)
        debug.draw(screen)


# ---- Recommended: don't modify anything below this line ---- #
if __name__ == "__main__":
    try:
        # Note: your editor might say that this is an error, but it's not.
        # Most editors can't understand that we are messing with the path.
        import wclib
    except ImportError:
        # wclib may not be in the path because of the architecture
        # of all the challenges and the fact that there are many
        # way to run them (through the showcase, or on their own)
        ROOT_FOLDER = Path(__file__).absolute().parent.parent.parent
        sys.path.append(str(ROOT_FOLDER))
        import wclib

    wclib.run(mainloop())
